M48
; DRILL file {KiCad 7.99.0-3958-g1df84f4d92} date 2023-12-24T01:26:04+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-24T01:26:04+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.99.0-3958-g1df84f4d92
; #@! TF.FileFunction,NonPlated,1,8,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
%
G90
G05
T1
X2.916Y-4.9821
T2
X5.1876Y-4.9821
M30
